os: linux
dist: xenial

language: php

# gh-151: disable tarantoo-2.2 due to lack of support the new
# _index format.
#
# Disable tarantool-1.6 and 1.7 on php 7.1-7.4, because
# php-7.[1-4]-cli docker images are based on Debian Buster, but we
# have no tarantool-1.[6-7] packages for this distribution.
jobs:
  include:
    # PHP 7.0
    # -------
    - php: 7.0
      env: TARANTOOL_VERSION=1.6
    - php: 7.0
      env: TARANTOOL_VERSION=1.7
    - php: 7.0
      env: TARANTOOL_VERSION=1.9
    - php: 7.0
      env: TARANTOOL_VERSION=1.10
    - php: 7.0
      env: TARANTOOL_VERSION=2.1
    # - php: 7.0
    #   env: TARANTOOL_VERSION=2.2
    - php: 7.0
      env: TARANTOOL_VERSION=2.3
    - php: 7.0
      env: TARANTOOL_VERSION=2.4

    # PHP 7.1
    # -------
    - php: 7.1
      env: TARANTOOL_VERSION=1.9
    - php: 7.1
      env: TARANTOOL_VERSION=1.10
    - php: 7.1
      env: TARANTOOL_VERSION=2.1
    # - php: 7.1
    #   env: TARANTOOL_VERSION=2.2
    - php: 7.1
      env: TARANTOOL_VERSION=2.3
    - php: 7.1
      env: TARANTOOL_VERSION=2.4

    # PHP 7.2
    # -------
    - php: 7.2
      env: TARANTOOL_VERSION=1.9
    - php: 7.2
      env: TARANTOOL_VERSION=1.10
    - php: 7.2
      env: TARANTOOL_VERSION=2.1
    # - php: 7.2
    #   env: TARANTOOL_VERSION=2.2
    - php: 7.2
      env: TARANTOOL_VERSION=2.3
    - php: 7.2
      env: TARANTOOL_VERSION=2.4

    # PHP 7.3
    # -------
    - php: 7.3
      env: TARANTOOL_VERSION=1.9
    - php: 7.3
      env: TARANTOOL_VERSION=1.10
    - php: 7.3
      env: TARANTOOL_VERSION=2.1
    # - php: 7.3
    #   env: TARANTOOL_VERSION=2.2
    - php: 7.3
      env: TARANTOOL_VERSION=2.3
    - php: 7.3
      env: TARANTOOL_VERSION=2.4

    # PHP 7.4
    # -------
    - php: 7.4
      env: TARANTOOL_VERSION=1.9
    - php: 7.4
      env: TARANTOOL_VERSION=1.10
    - php: 7.4
      env: TARANTOOL_VERSION=2.1
    # - php: 7.4
    #   env: TARANTOOL_VERSION=2.2
    - php: 7.4
      env: TARANTOOL_VERSION=2.3
    - php: 7.4
      env: TARANTOOL_VERSION=2.4

    # RPM packages
    # ------------
    # Note: CentOS 6 & 7 do not provide PHP 7.*.
    # Note: Fedora < 25 do not provide PHP 7.*.
    - env: OS=el DIST=8
    - env: OS=fedora DIST=25
    - env: OS=fedora DIST=26
    - env: OS=fedora DIST=27
    - env: OS=fedora DIST=28
    - env: OS=fedora DIST=29
    - env: OS=fedora DIST=30
    - env: OS=fedora DIST=31

    # Deb packages
    # ------------
    # Debian < 8 (Stretch) do not provide PHP 7.*.
    # Ubuntu < 16.04 (Xenial) do not provide PHP 7.*.
    - env: OS=debian DIST=stretch
    - env: OS=debian DIST=buster
    - env: OS=ubuntu DIST=xenial
    - env: OS=ubuntu DIST=bionic
    - env: OS=ubuntu DIST=eoan
    - env: OS=ubuntu DIST=focal

python:
  - 2.7

script:
  - |
    if [ -n "${TARANTOOL_VERSION}" ]; then
        ./test.sh
    elif [ -n "${OS}" ] && [ -n "${DIST}" ]; then
        git clone --depth 1 https://github.com/packpack/packpack.git
        ./packpack/packpack
        if [ "${OS}" = "el" ]; then
            export OS=centos
        fi
        docker run \
            --volume "$(realpath .):/tarantool-php" \
            --workdir /tarantool-php                \
            --rm                                    \
            "${OS}:${DIST}"                         \
            ./test.pkg.sh
    else
        exit 1
    fi
